- id: julia-formatter
  name: "Julia Formatter"
  entry: "jlfmt --inplace"
  pass_filenames: true
  always_run: false
  types: [file]
  files: \.(jl|[jq]?md)$
  language: "system"
  description: "An opinionated code formatter for Julia. Plot twist - the opinion is your own."
