- id: julia-formatter
  name: "Julia Formatter"
  entry: "./bin/format.jl ."
  pass_filenames: false
  always_run: true
  language: "system"
  description: "An opinionated code formatter for Julia. Plot twist - the opinion is your own."